name: consistency_test

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'docker/**'
      - '.github/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'docker/**'
      - '.github/**'

jobs:
  docker-branch-os-matrix:
    name: build docker and run tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # - name: Login to DockerHub
        #   uses: docker/login-action@v1
        #   # with:
        #   #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   #   password: ${{ secrets.DOCKERHUB_TOKEN  }}
        # - name: Build
        #   id: docker_build
        #   uses: docker/build-push-action@v3
        #   with:
        #     context: .
        #     tags: docker-cpu:1.0
        #     file: docker/docker-cpu/Dockerfile
        # - name: Image digest
        #   run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Build
        run: docker build docker/docker-cpu -t docker-cpu:1.0
        # with:
        #   context: .
      - name: Download test data
        run: |
          pip install zenodo_get && \
          zenodo_get 7040177 -o /tmp/ && \
          7z x /tmp/venus_clouds_v1.0.7z -o/tmp/training_data && \
          rm /tmp/training_data/training_set_clouds_multiclass/s*
      - name: Test1
        run: |
          docker run --rm -v /tmp:/tmp:rw -v ${GITHUB_WORKSPACE}/src:/src:ro -e PYTHONPATH=/usr/local/lib/python3.6/dist-packages:/usr/local/lib/python3/dist-packages:/src --cpus=2 -m 20g docker-cpu:1.0 pytest src/test/consistency_test.py
